[package]
name = "try_rustpython"
version = "0.1.0"
authors = ["Oliver Calder <oacalder@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython-compiler = "0.1.2"
rustpython-vm = "0.1.2"
